{"name": "test_mul[get_datas_mul0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <pratice_demo.pratice_calculator_advanced.test_calc_new.TestCalculator object at 0x00000227C9CA2730>\nget_calc = <pratice_demo.pratice_calculator_advanced.demo.calc.Calculator object at 0x00000227C9B9A520>, get_datas_mul = [999999999.1, 1, 999999999.1]\n\n    @allure.story(\"计算器的乘法测试\")\n    @pytest.mark.run(order=3)\n    def test_mul(self, get_calc, get_datas_mul):\n        if get_datas_mul[0] > 999999999 or get_datas_mul[1] > 999999999:\n            print(\"超出最大数值999999999，不允许输出\")\n>           assert False\nE           assert False\n\ntest_calc_new.py:170: AssertionError"}, "attachments": [{"name": "stdout", "source": "eb872532-4b14-49dc-b399-20137cc5abf7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_mul", "value": "[999999999.1, 1, 999999999.1]"}], "start": 1612345233680, "stop": 1612345233680, "uuid": "de029936-4f01-4ad2-ab67-4f65bf02d7b8", "historyId": "7bd0b4db331b4f796d5ae39e9799260b", "testCaseId": "bf91843f7e3da214fab11bfe24640dc5", "fullName": "test_calc_new.TestCalculator#test_mul", "labels": [{"name": "story", "value": "计算器的乘法测试"}, {"name": "feature", "value": "测试计算器"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "Naraku15"}, {"name": "thread", "value": "6112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}