{"name": "test_mul[get_datas_mul2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <pratice_demo.pratice_calculator_advanced.test_calc_new.TestCalculator object at 0x0000024314F56EB0>\nget_calc = <pratice_demo.pratice_calculator_advanced.demo.calc.Calculator object at 0x0000024314E8D550>, get_datas_mul = [1, 999999999.1, 999999999.1]\n\n    @allure.story(\"计算器的乘法测试\")\n    @pytest.mark.run(order=3)\n    def test_mul(self, get_calc, get_datas_mul):\n        if get_datas_mul[0] > 999999999 or get_datas_mul[1] > 999999999:\n            print(\"超出最大数值999999999，不允许输出\")\n>           assert False\nE           assert False\n\ntest_calc_new.py:170: AssertionError"}, "attachments": [{"name": "stdout", "source": "edba1ddc-4615-4b85-9bdf-0722e3a79166-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_mul", "value": "[1, 999999999.1, 999999999.1]"}], "start": 1612345709706, "stop": 1612345709707, "uuid": "cfe99b9b-eb70-4062-86d7-d361932d603a", "historyId": "490fa63fb2310ccc32680dbd72f6122e", "testCaseId": "bf91843f7e3da214fab11bfe24640dc5", "fullName": "test_calc_new.TestCalculator#test_mul", "labels": [{"name": "story", "value": "计算器的乘法测试"}, {"name": "feature", "value": "测试计算器"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "Naraku15"}, {"name": "thread", "value": "10164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}