{"name": "test_mul[get_datas_mul3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <pratice_demo.pratice_calculator_advanced.test_calc_new.TestCalculator object at 0x00000227C9CA2670>\nget_calc = <pratice_demo.pratice_calculator_advanced.demo.calc.Calculator object at 0x00000227C9B9A520>, get_datas_mul = [-1, -999999999.1, 999999999.1]\n\n    @allure.story(\"计算器的乘法测试\")\n    @pytest.mark.run(order=3)\n    def test_mul(self, get_calc, get_datas_mul):\n        if get_datas_mul[0] > 999999999 or get_datas_mul[1] > 999999999:\n            print(\"超出最大数值999999999，不允许输出\")\n            assert False\n        # 假设最小能输入-999999999\n        elif get_datas_mul[0] < -999999999 or get_datas_mul[1] < -999999999:\n            print(\"超出最小数值-999999999，不允许输出\")\n>           assert False\nE           assert False\n\ntest_calc_new.py:174: AssertionError"}, "attachments": [{"name": "stdout", "source": "c39971bc-7622-46bf-97ed-f0fbd51c6cbc-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_mul", "value": "[-1, -999999999.1, 999999999.1]"}], "start": 1612345233706, "stop": 1612345233707, "uuid": "21776f4e-58ac-4e8f-94bc-f43c3c8e2ba9", "historyId": "6d3fb21b3dcfa1bf8a94869dee189c5e", "testCaseId": "bf91843f7e3da214fab11bfe24640dc5", "fullName": "test_calc_new.TestCalculator#test_mul", "labels": [{"name": "story", "value": "计算器的乘法测试"}, {"name": "feature", "value": "测试计算器"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "Naraku15"}, {"name": "thread", "value": "6112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}