{"name": "test_div[get_datas_div2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <pratice_demo.pratice_calculator_advanced.test_calc_new.TestCalculator object at 0x0000024314F58FA0>\nget_calc = <pratice_demo.pratice_calculator_advanced.demo.calc.Calculator object at 0x0000024314E8D550>, get_datas_div = [999999999.9, 1, 999999999.9]\n\n    @allure.story(\"计算器的除法测试\")\n    @pytest.mark.run(order=4)\n    def test_div(self, get_calc, get_datas_div):\n        # 假设最大能输入999999999\n        if get_datas_div[0] > 999999999 or get_datas_div[1] > 999999999:\n            print(\"超出最大数值999999999，不允许输出\")\n>           assert False\nE           assert False\n\ntest_calc_new.py:102: AssertionError"}, "attachments": [{"name": "stdout", "source": "7e9cb9ab-c5b6-4e5a-94e7-92030354089a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_div", "value": "[999999999.9, 1, 999999999.9]"}], "start": 1612345709827, "stop": 1612345709827, "uuid": "ccd20ab7-0241-44ab-bb41-12493db443f1", "historyId": "55d87b978e1812afddcc40b761590607", "testCaseId": "0134be1d683a1f54a7e80c7783a2eb76", "fullName": "test_calc_new.TestCalculator#test_div", "labels": [{"name": "feature", "value": "测试计算器"}, {"name": "story", "value": "计算器的除法测试"}, {"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "Naraku15"}, {"name": "thread", "value": "10164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}