{"name": "test_mul[get_datas_mul2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <pratice_demo.pratice_calculator_advanced.test_calc_new.TestCalculator object at 0x00000227C9C60BB0>\nget_calc = <pratice_demo.pratice_calculator_advanced.demo.calc.Calculator object at 0x00000227C9B9A520>, get_datas_mul = [1, 999999999.1, 999999999.1]\n\n    @allure.story(\"计算器的乘法测试\")\n    @pytest.mark.run(order=3)\n    def test_mul(self, get_calc, get_datas_mul):\n        if get_datas_mul[0] > 999999999 or get_datas_mul[1] > 999999999:\n            print(\"超出最大数值999999999，不允许输出\")\n>           assert False\nE           assert False\n\ntest_calc_new.py:170: AssertionError"}, "attachments": [{"name": "stdout", "source": "b831bf6a-71ac-4341-890d-ea9157ee90b7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_mul", "value": "[1, 999999999.1, 999999999.1]"}], "start": 1612345233698, "stop": 1612345233698, "uuid": "c3409953-2afa-4d7e-b0a8-2e19c04b570b", "historyId": "490fa63fb2310ccc32680dbd72f6122e", "testCaseId": "bf91843f7e3da214fab11bfe24640dc5", "fullName": "test_calc_new.TestCalculator#test_mul", "labels": [{"name": "story", "value": "计算器的乘法测试"}, {"name": "feature", "value": "测试计算器"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "Naraku15"}, {"name": "thread", "value": "6112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}