{"name": "test_div[get_datas_div4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <pratice_demo.pratice_calculator_advanced.test_calc_new.TestCalculator object at 0x00000227C9C709A0>\nget_calc = <pratice_demo.pratice_calculator_advanced.demo.calc.Calculator object at 0x00000227C9B9A520>, get_datas_div = [1, 999999999.9, 0]\n\n    @allure.story(\"计算器的除法测试\")\n    @pytest.mark.run(order=4)\n    def test_div(self, get_calc, get_datas_div):\n        # 假设最大能输入999999999\n        if get_datas_div[0] > 999999999 or get_datas_div[1] > 999999999:\n            print(\"超出最大数值999999999，不允许输出\")\n>           assert False\nE           assert False\n\ntest_calc_new.py:102: AssertionError"}, "attachments": [{"name": "stdout", "source": "97d0a72c-7532-41f7-992c-e79174985ae3-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_div", "value": "[1, 999999999.9, 0]"}], "start": 1612345233841, "stop": 1612345233841, "uuid": "ac1d05d8-8abd-4d37-8aa2-999a476cc7c8", "historyId": "aa944e9e112d5dfd11560def102fe072", "testCaseId": "0134be1d683a1f54a7e80c7783a2eb76", "fullName": "test_calc_new.TestCalculator#test_div", "labels": [{"name": "feature", "value": "测试计算器"}, {"name": "story", "value": "计算器的除法测试"}, {"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "Naraku15"}, {"name": "thread", "value": "6112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}